### PR TITLE
comment markup improvements

### PR DESCRIPTION
**Pull request by xi**
While trying to style the a4 comments for meinberlin I found some issues with the markup:

- `<a href="#">` was used instead of `<button>`
- `class="icon fa-*"` was used instead of a `<i class="fa fa-*">` child (see [CSS in euth_wagtail](https://github.com/liqd/euth_wagtail/blob/40dd0be976073e92ca97a9041abcdc5c6a8c2350/euth_wagtail/assets/scss/components/_comments.scss#L73))
- `aria-hidden="true"` was used for essential elements

### CODE REVIEW

**Comment by MagdaN** [comment]
@xi did you test this? This might break some stuff, e.g. using buttons instead of anchors might cause some problems.

**Comment by xi** [comment]
Sorry, I should have said this in the original description: I could not test it as comments do not work yet in a4-meinberlin.

I don't expect any breakage in terms of functionality, but the styling in euth_wagtail will probably need to be adapted.

**Comment by MagdaN** [comment]
@xi I remember having some functional issues with using buttons instead of anchors, maybe you just test this

**Comment by xi** [comment]
Ok, I did the test. Works fine for me.

**Comment by xi** [comment]
I added some more classes to make styling easier:

- `dropdown-item` (which also exists in bootstrap4) (c25db1d)
- `comment-reply-button` (6d74c81)

**Comment by slomo** [comment]
works on opin (even without using `dropdown-item` but with `comment-reply-button`) see https://github.com/liqd/euth_wagtail/tree/2017-02-adopt-to-new-comment-markup

**Pull request merged**
