### PR TITLE
comments: move date conversion to own function and use in serializer

### PR DESCRIPTION
**Pull request by Rineee**
I moved the date conversion to a function, so we can use it in other places. I guess it would better fit into contrib, but we dont have that in a4, so left it in comments app for now.. could also create contrib folder?

### CODE REVIEW

**Review by fuzzylogic2000 — COMMENTED** [review]
Looks good!
Could it go to api as a helper as that is where we use it?
And when do we add tests? :)

**Comment by Rineee** [comment]
> Looks good! Could it go to api as a helper as that is where we use it? And when do we add tests? :)

Yeah, I also thought about that, but we are actually using it in the serializers and in the api folder, there is only router stuff.. so I thought it does also not quite fit there? But maybe better than comments.. So: you prefer putting it to api instead of making a contrib folder?

I will add a test with the other tests, its on the list!

**Comment by Rineee** [comment]
> > Looks good! Could it go to api as a helper as that is where we use it? And when do we add tests? :)
> 
> Yeah, I also thought about that, but we are actually using it in the serializers and in the api folder, there is only router stuff.. so I thought it does also not quite fit there? But maybe better than comments.. So: you prefer putting it to api instead of making a contrib folder?
> 
> I will add a test with the other tests, its on the list!

Alright, moved it to api now as definitely better than comments and then we can merge!

**Review by fuzzylogic2000 — APPROVED** [review]
Very nice!

**Pull request merged**
