### PR TITLE
comments_async: update logic for termsofuse checkbox to ensure it's s…

### PR DESCRIPTION
**Pull request by phillimorland**
…hown on edit

### CODE REVIEW

**Review by fuzzylogic2000 — COMMENTED** [review]
It still does not show the checkbox to me, when I edit a reply. But it changes the state and then does not show the checkbox at all (also in the create forms) anymore when I update the reply. It does not save the agreement, though. Reloading the comments shows the checkbox again in the create forms.

**Comment by phillimorland** [comment]
@fuzzylogic2000 what??? so no checkbox on reply edit and no checkbox on comment??? I'm seeing this right now: will try a reinstall and link though as it was being very slow, maybe I removed something before commit.
Screenshot from 2022-06-21 15-43-28

**Comment by phillimorland** [comment]
sorry ran lint fix and it did a whole bunch of other crap but that should now work

**Review by fuzzylogic2000 — APPROVED** [review]
Nice!

**Pull request merged**
