### PR TITLE
Ks 2021 09 add poll export

### PR DESCRIPTION
**Pull request by Rineee**

### CODE REVIEW

**Comment by Rineee** [comment]
oh no, tests are failing... will fix it first thing tomorrow

**Review by fuzzylogic2000 — APPROVED** [review]
Very nice!

**Comment by fuzzylogic2000** [comment]
> oh no, tests are failing... will fix it first thing tomorrow

Ha, right! Feel free to merge this (and the other PRs) when that's done!

**Comment by Rineee** [comment]
@fuzzylogic2000 I know changed this again as I couldnt adjust the urls.. so now in a4 and mB the components only have module as kwargs and in aplus the organisation_slug is added (was the other way around before).
Could you check one last time if everything is fine? Sorry for the double work :grimacing: 

https://github.com/liqd/a4-meinberlin/pull/3882
https://github.com/liqd/adhocracy-plus/pull/1454

And very sorry for almost 1% less coverage :scream:  I will take care of it on Monday!

**Comment by fuzzylogic2000** [comment]
Yeah, it still works fine in both projects!
Do you want to write the tests first and then merge? Or merge now and then add the tests?

**Comment by Rineee** [comment]
I branched off, so lets merge first, so it can already be tested!

**Comment by fuzzylogic2000** [comment]
And you will update a4 in the projects, right?

**Comment by Rineee** [comment]
Yes!

**Pull request merged**
