### PR TITLE
update fontawesome - use new classnames

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
There is already a PR (https://github.com/liqd/a4-meinberlin/pull/1243) in meinBerlin using the new fontawesome. But before merging, we need to also update the other projects.

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
Polls in meinBerlin? They should work.
OPIN? Don't know, you should be able to see it in the settings

**Comment by phillimorland** [comment]
Yeah OPIN polls, what am I looking for in settings? the flashpolls are in base.py but thats its as far as poll stuff goes

**Comment by fuzzylogic2000** [comment]
Yes! When these (https://github.com/liqd/a4-opin/blob/64e6341b99ce75cdf77e2e3b5224464ef72a8ab1/euth_wagtail/settings/base.py#L84) are not yet in there it's because they are in the master, but not yet in that branch

**Comment by phillimorland** [comment]
ok, I didn't find any other issues for opin and mein, still setting up advocate to test

**Pull request merged**
