### PR TITLE
add tile image to project

### PR DESCRIPTION
**Pull request by 2e2a**
The aspects of the tile image and the heroimage is too different. Cropping the heroimage to the tile does not work in general.

### CODE REVIEW

**Comment by kleingeist** [comment]
just a note: old images (due to modifications/deletions) are currently not automatically deleted. for projectes a signal is used to delete them (see [0])
some time ago i did rewrite the delete images signals to act on every image field found (see [1]) but those changes are not merges yet.
@slomo did vote against signals and would prefer a cronjob which deletes old images regularly. 


[0] https://github.com/liqd/adhocracy4/blob/master/adhocracy4/projects/signals.py
[1] https://github.com/liqd/adhocracy4/compare/2017-06-jd-move-images-signals

**Comment by slomo** [comment]
Since this just adds additional fields, I would merge this. I have just two additional points here: 

 1. Has this been taken though some design process for adhocracy4 in general. Or asked differently should we adopt other platforms here? ( @damusp )
 2.  Even though I am on a personal vendetta with signals, we should probably delete those files somehow and keep it consistent. So I would say we should right now also add/extend signals for the tile image field. (Was that also your point? @kleingeist )

**Comment by 2e2a** [comment]
> Has this been taken though some design process for adhocracy4 in general. Or asked differently should we adopt other platforms here? ( @damusp )

No, this was not a design decision, but a reaction to customer complains.
But we can discuss this for other projects, as the problem is there too.

**Comment by 2e2a** [comment]
> Even though I am on a personal vendetta with signals, we should probably delete those files somehow and keep it consistent. So I would say we should right now also add/extend signals for the tile image field. (Was that also your point? @kleingeist )

Will add the delete signals.

**Comment by kleingeist** [comment]
> Even though I am on a personal vendetta with signals, we should probably delete those files somehow and keep it consistent. So I would say we should right now also add/extend signals for the tile image field. (Was that also your point? @kleingeist )

@slomo yes, i linked to my branch which registers signals for all ConfiguredImageFields on django initialization.
@2e2a, @slomo what is your opinion on the general approach? i'd apparently would prefer it over the explicit registration of delete handlers for every ConfiguredImaged.

**Pull request merged**
