### PR TITLE
comments_async: Support markdown in comments

### LINKED ISSUE #629: Include link in comment
**URL:** https://beteiligung.zukunftsgewerkschaft.de/subjects/2020-00683/
**user:** moderator
**expected behaviour:** I can insert a link as a hyperlink in a comment
**behaviour:** I can insert a link, but it is no hyperlink and not clickable

**Comment/Question:** Is this a feature request?

### PR DESCRIPTION
**Pull request by rmader**
This makes us render comments similar to what e.g. github does.

See https://github.com/remarkjs/react-markdown

Closes #629

### CODE REVIEW

**Comment by rmader** [comment]
This probably needs a go from PMs... @fredewe @hmkay @rittermo, opinions on this?

**Comment by rmader** [comment]
Here's how it would look like:
image

**Comment by hmkay** [comment]
I guess this is for @fredewe . Only remark I have is the usability for mobile users. Is it easy or too complicated to have these options?

**Comment by fuzzylogic2000** [comment]
And shoudn't we also change the helptext if we do this?

**Comment by rmader** [comment]
We do not yet have any visible helpers...IMHO most users who want to use such features already know them - or don't need them. The requested feature was being able to paste urls and getting them recognised - this happens automatically now.

**Comment by fredewe** [comment]
It seems to be a nice feature and i like it. So it would be a "go" from my side.

**Review by fuzzylogic2000 — APPROVED** [review]
It's just too cool! But I still think, we should maybe add some helptext, so that people know how to use it! (and I merge now, because for people using it, this doesn't make a difference, I would say)

**Pull request merged**
