### PR TITLE
modules/predicates: make some predicates work for projects instead of…

### PR DESCRIPTION
**Pull request by Rineee**
… items

I needed this for the moderation comments permission as we don't have a module there, so the permission object (for creating) needs to be the project.

### CODE REVIEW

**Review by fuzzylogic2000 — APPROVED** [review]
Ah, I needed a while to get why you need that. But ok! :)

**Comment by fuzzylogic2000** [comment]
Right! You should add it to the tests, though. I think we do test the predicates and rules quite extensively so far. You can do it in this PR or add a task and merge this one.

**Comment by Rineee** [comment]
> Right! You should add it to the tests, though. I think we do test the predicates and rules quite extensively so far. You can do it in this PR or add a task and merge this one.

@fuzzylogic2000 Voilà!

**Review by fuzzylogic2000 — APPROVED** [review]
Nice!

**Pull request merged**
