### PR TITLE
Add archive flag to project

### PR DESCRIPTION
**Pull request by 2e2a**

### CODE REVIEW

**Comment by xi** [comment]
What is the exact semantics of this? How does it relate to "all phases of all modules have ended"?

**Comment by 2e2a** [comment]
> What is the exact semantics of this? How does it relate to "all phases of all modules have ended"?

This relation is not defined in core and can be decided in each project, e.g. by showing this setting only if participation is over.

**Comment by xi** [comment]
I don't think it is a good idea to have flags in core that do not have clear semantics.

From your answer I guess the intended semantics are roughly "Even if a project has completed all of its participation, it may still be active in other ways. This flag allows to distinguish these projects from truly archived ones."

**Comment by 2e2a** [comment]
Yes, that's way to define it.

**Comment by MagdaN** [comment]
LGTM please merge, if you are fine with it

**Pull request merged**
