### PR TITLE
comments_async: Show number of replies to comment (if applicable)

### PR DESCRIPTION
**Pull request by rmader**
Some more drive-by stuff - needs design/ux approval :)

Closes https://github.com/liqd/adhocracy-plus/issues/958

Pic1:
Screenshot_2020-11-17 adhocracy+ liqd-orga

Pic2:
Screenshot_2020-11-17 adhocracy+ liqd-orga2

Pic3:
Screenshot_2020-11-17 adhocracy+ liqd-orga3

### CODE REVIEW

**Review by fuzzylogic2000 — APPROVED** [review]
:+1:

**Comment by fredewe** [comment]
I like it :) @mcastro-lqd what would you say?

**Comment by mcastro-lqd** [comment]
Both are fine for me @rmader 

If I would change something, I would just avoid 2 lines like that, but Idk if that's possible 

Thanks :)

Screenshot-2020-11-18-at-16 25 18

**Comment by rmader** [comment]
Thanks! Actually it's three different pictures, so the double line was from different ones. I added some space to make that more visible.

**Pull request merged**
