### PR TITLE
Categories app

### PR DESCRIPTION
**Pull request by 2e2a**
Add the following models:
- `Category`: categories that belong to a module.
- `Categorizable`: Add a category field to another model, e.g. Item

### CODE REVIEW

**Comment by MagdaN** [comment]
Looks good, I just have one issue which came to my mind just know: How can we translate a category?

**Comment by 2e2a** [comment]
> Looks good, I just have one issue which came to my mind just know: How can we translate a category?

It might not need translation, as it is user generated content.

**Comment by 2e2a** [comment]
Need to discuss how to enable/configure it.

**Comment by 2e2a** [comment]
Not extending UserGeneratedModel anymore, as the creator can be received from `module.project`.

**Pull request merged**
