### PR TITLE
Pm 2021 07 comment bs issue fixes

### PR DESCRIPTION
**Pull request by phillimorland**

### CODE REVIEW

**Review by fuzzylogic2000 — COMMENTED** [review]
It looks good! But I am not sure, I can fix the conflicts... Can you have a go, @phillimorland ?

**Comment by phillimorland** [comment]
@fuzzylogic2000 just doing it now

**Comment by phillimorland** [comment]
@fuzzylogic2000 ignore re-tag just yet, will tag you when have it working properly

**Comment by phillimorland** [comment]
@fuzzylogic2000 now should be ready

**Review by fuzzylogic2000 — APPROVED** [review]
@phillimorland And now it is ready for you in turn!
Everything you added already works, when the link-text thingy also works for you, you can merge!

**Comment by phillimorland** [comment]
@fuzzylogic2000 awesome! :)

**Pull request merged**
