### PR TITLE
React 18: static/*: update render functions to react18 syntax

### PR DESCRIPTION
**Pull request by phillimorland**
This PR will make a4 unusable in all other projects!

### CODE REVIEW

**Review by goapunk — APPROVED** [review]
Looks good to me, however the comments are still broken, right? How should we do this?

**Comment by phillimorland** [comment]
@goapunk I still haven't reviewed your PR yet but can do that next and maybe we merge that one then this, does that make sense?

**Comment by goapunk** [comment]
> @goapunk I still haven't reviewed your PR yet but can do that next and maybe we merge that one then this, does that make sense?

@phillimorland sounds good to me

**Comment by phillimorland** [comment]
@goapunk so shall we merge here?

**Comment by goapunk** [comment]
@phillimorland yeah lets give it a try

**Pull request merged**
